-- Migration: Add form-based rankings and home/away strength to team_rankings table
-- Purpose: Enable fixture difficulty prediction based on recent form (last 5 GWs) 
--          and home/away performance (last 10 GWs) instead of static season FDR

-- ┌─ Form-based Rankings (Last 5 GWs) ────────────────────────────────────────┐
-- │ These columns track attack/defense performance over the most recent 5 games  │
-- │ to provide a more current view of team strength for fixture difficulty      │
-- └────────────────────────────────────────────────────────────────────────────┘

ALTER TABLE team_rankings ADD COLUMN IF NOT EXISTS last_5_goals FLOAT DEFAULT 0;
-- Total goals scored by team in last 5 gameweeks (from starters only)

ALTER TABLE team_rankings ADD COLUMN IF NOT EXISTS last_5_assists FLOAT DEFAULT 0;
-- Total assists generated by team in last 5 gameweeks

ALTER TABLE team_rankings ADD COLUMN IF NOT EXISTS last_5_clean_sheets INT DEFAULT 0;
-- Number of clean sheets in last 5 gameweeks

ALTER TABLE team_rankings ADD COLUMN IF NOT EXISTS last_5_goals_conceded INT DEFAULT 0;
-- Total goals conceded by team in last 5 gameweeks

ALTER TABLE team_rankings ADD COLUMN IF NOT EXISTS attack_rank_5 INT DEFAULT 1;
-- Ranking 1-20 for attack strength based on last 5 GWs only
-- 1 = strongest attacking form, 20 = weakest

ALTER TABLE team_rankings ADD COLUMN IF NOT EXISTS defense_rank_5 INT DEFAULT 1;
-- Ranking 1-20 for defensive strength based on last 5 GWs only
-- 1 = strongest defensive form, 20 = weakest

ALTER TABLE team_rankings ADD COLUMN IF NOT EXISTS attack_score_5 FLOAT DEFAULT 0;
-- Calculated attack strength for last 5 GWs (used for ranking)

ALTER TABLE team_rankings ADD COLUMN IF NOT EXISTS defense_score_5 FLOAT DEFAULT 0;
-- Calculated defense strength for last 5 GWs (used for ranking)

-- ┌─ Home/Away Strength (Last 10 GWs) ───────────────────────────────────────┐
-- │ These columns quantify whether a team is stronger/weaker at home vs away    │
-- │ Modifiers are -50 to +50: positive = team stronger at home                  │
-- └────────────────────────────────────────────────────────────────────────────┘

ALTER TABLE team_rankings ADD COLUMN IF NOT EXISTS last_10_home_goals FLOAT DEFAULT 0;
-- Goals scored at home in last 10 gameweeks

ALTER TABLE team_rankings ADD COLUMN IF NOT EXISTS last_10_away_goals FLOAT DEFAULT 0;
-- Goals scored away in last 10 gameweeks

ALTER TABLE team_rankings ADD COLUMN IF NOT EXISTS last_10_home_clean_sheets INT DEFAULT 0;
-- Clean sheets at home in last 10 gameweeks

ALTER TABLE team_rankings ADD COLUMN IF NOT EXISTS last_10_away_clean_sheets INT DEFAULT 0;
-- Clean sheets away in last 10 gameweeks

ALTER TABLE team_rankings ADD COLUMN IF NOT EXISTS home_strength_10 FLOAT DEFAULT 0;
-- Home ground advantage modifier (-50 to +50)
-- +50 = team significantly stronger at home
-- 0 = no home/away difference
-- -50 = team significantly weaker at home

ALTER TABLE team_rankings ADD COLUMN IF NOT EXISTS away_strength_10 FLOAT DEFAULT 0;
-- Away ground weakness modifier (-50 to +50)
-- This is automatically set to -home_strength_10 to represent away weakness

-- ┌─ Indexing for Performance ───────────────────────────────────────────────┐
CREATE INDEX IF NOT EXISTS idx_team_rankings_attack_rank_5 ON team_rankings(attack_rank_5);
CREATE INDEX IF NOT EXISTS idx_team_rankings_defense_rank_5 ON team_rankings(defense_rank_5);

-- Verification query to test columns exist:
-- SELECT last_5_goals, attack_rank_5, home_strength_10 
-- FROM team_rankings LIMIT 1;
